version: "3.7"
services:
  overdue:
    container_name: overdue
    restart: always
    build: .
    working_dir: /usr/app/backend
    command: yarn start
    environment:
      SERVICE_NAME: overdue-customers
      SERVICE_TAGS: dev
      SERVICE_DB_HOST: mongodb:27017
      SERVICE_DB_USER: root
      SERVICE_DB_PASSWORD: ''
    volumes:
      
      - /usr/app/frontend/node_modules
      - /usr/app/backend/node_modules
    depends_on:
      - mongo
    ports:
      - 3000:3000
    networks:
      - nest-network

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge
volumes:
  db_data: {}