version: "3.5"

services:
  nestjs:
    build:
      context: ./packages/nestjs
      dockerfile: Dockerfile.dev
    env_file:
     - ./packages/nestjs/.env
    ports:
      - 3000:3000
    volumes:
      - ./packages/nestjs/:/app/backend
      - /app/backend/node_modules
      - frontend:/app/backend/public

  angular:
    build:
      context: ./packages/angular
      dockerfile: Dockerfile.dev
    volumes:
      - ./packages/angular/:/app/frontend
      - /app/frontend/node_modules
      - frontend:/app/frontend/dist

  mongo:
    container_name: mongodb
    image: mongo
    volumes:
      - db_data:/data/db
    ports:
      - 27017:27017

volumes:
  db_data: {}
  frontend: {}